name: IPTV Otomatik Guncelleme

on:
  schedule:
    # Her 4 saatte bir (00:00, 04:00, 08:00 vb. UTC saatiyle)
    - cron: '0 */4 * * *'
  workflow_dispatch: # Manuel çalıştırma butonu ekler

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Bagimliliklari Yukle
        run: |
          pip install requests
          # En güncel yt-dlp'yi indir ve yetki ver
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp

      - name: Scripti Calistir
        run: python Cloud.py
